// Generated by CoffeeScript 2.2.2
(function() {
  var coffee, coffeeSrc, gulp, jsPublic;

  gulp = require('gulp');

  coffee = require('gulp-coffee');

  coffeeSrc = './src/*.coffee';

  jsPublic = './public/';

  gulp.task('coffee', function() {
    return gulp.src(coffeeSrc).pipe(coffee({
      bare: true
    })).pipe(gulp.dest(jsPublic));
  });

  gulp.task('watchCoffee', function() {
    return gulp.watch(coffeeSrc, ['coffee']);
  });

}).call(this);
