// Generated by CoffeeScript 2.2.2
(function() {
  var $, applications, applicationsFolder, cacheFile, createText, fs, input, oldApps, parseApplications, readAppName, remote, removeText, runApplication, spawn;

  fs = require('fs');

  $ = require('jQuery');

  remote = require('electron').remote;

  spawn = require('child_process').spawn;

  applicationsFolder = '/usr/share/applications/';

  cacheFile = './cachefile';

  applications = [];

  oldApps = [];

  parseApplications = function() {
    var cacheData, cacheDataJson, dateNow;
    cacheData = fs.readFileSync(cacheFile, 'utf8');
    cacheData = JSON.parse(cacheData);
    dateNow = Date.now() / 1000 | 0;
    if (cacheData.expirations === void 0 || cacheData.expirations < dateNow) {
      fs.readdirSync(applicationsFolder).forEach(function(file) {
        var contents, found, re;
        contents = fs.readFileSync(applicationsFolder + file, 'utf8');
        re = /Name=(.*)/;
        found = contents.match(re);
        if (found && found[1].length) {
          return applications.push(found[1]);
        }
      });
      cacheData = {
        'expirations': dateNow + 360,
        'applications': applications
      };
      cacheDataJson = JSON.stringify(cacheData);
      return fs.writeFileSync(cacheFile, cacheDataJson);
    } else {
      return applications = cacheData.applications;
    }
  };

  readAppName = function(name) {
    var counter;
    oldApps = [];
    counter = 0;
    return applications.forEach(function(file) {
      if (file.toLowerCase().indexOf(name.toLowerCase()) !== -1 && counter < 5) {
        createText(++counter + '. ' + file);
        return oldApps.push(file);
      }
    });
  };

  createText = function(text) {
    var container, div;
    container = $('.container');
    div = document.createElement('div');
    div.textContent = text;
    div.className = 'text';
    return container.append(div);
  };

  removeText = function() {
    return $('.text').remove();
  };

  runApplication = function(name) {
    var ps;
    ps = spawn('wmctrl', ['-v', '-a', name]);
    return ps.stdout.on('data', function(data) {
      return console.log('stdout: ' + data);
    });
  };

  input = document.getElementById('appName');

  input.addEventListener('keyup', function(event) {
    var window;
    if ($.isNumeric(event.key)) {
      input.value = event.target.value.slice(0, -1);
      if (event.key > 0 && event.key < 6 && oldApps.length >= event.key) {
        runApplication(oldApps[event.key - 1]);
        window = remote.getCurrentWindow();
        return window.close();
      }
    } else if (event.key === 'Enter') {
      runApplication(oldApps[0]);
      window = remote.getCurrentWindow();
      return window.close();
    } else {
      removeText();
      return readAppName(event.target.value);
    }
  });

  input.focus();

  parseApplications();

}).call(this);
